version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo Into the pre_build phase...
      - python3 -m venv venv
      - source ./venv/bin/activate
  build:
    commands:
      - echo Running script
      - python3 code/testing.py
  post_build:
    commands:
      - echo Build completed on `date`
