AWSTemplateFormatVersion: '2010-09-09'
Description: Template to execute in CodeBuild
Parameters:
  Environment:
    Type: String
    Description: 'Tag and Environment values'
    AllowedValues:
      - QA
      - ''
    Default: QA
Resources:
  #MySourceCreds:
    #Type: AWS::CodeBuild::SourceCredential
    #Properties:
      #AuthType: PERSONAL_ACCESS_TOKEN
      #ServerType: GITHUB
      #Token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  CodeBuild:
    Type: AWS::CodeBuild::Project
    #DependsOn: MySourceCreds
    Properties:
      LogsConfig:
        CloudWatchLogs: 
          GroupName: "TestRepoLogs"
          Status: ENABLED
      Artifacts:
        Type: S3
        Location: testgit-output1
        Name: /
        Path: output1
      BadgeEnabled: false
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: public.ecr.aws/glue/aws-glue-libs:glue_libs_3.0.0_image_01
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name: "Testrepository-main-build6"
      ServiceRole: CodeBuildServiceRole2
      Source:
        Location: https://github.com/Abhi-Tom-2004/Testrepository.git
        BuildSpec: !Sub |
          version: 0.2
          env:
            shell: bash
            variables: 
              JUNIT_XML: junit_coverage.xml
          phases:
            pre_build:
              commands:
                - echo "Install dependencies"
                - python3 --version
                - python3 -m venv venv
                - source venv/bin/activate
                - pip3 install -r requirements.txt
                - echo "installation done"
                - cd "code"
                - echo "entering to code sub folder"
            build:
              commands:
                - echo "Running script"
                - python3 s3_conn.py
          artifacts:
            files:
              - '**/*'
            name: output2-$(date+%Y-%m-%d)
            base-directory: 'output'
            discard-paths: yes
        Type: GITHUB
      TimeoutInMinutes: 15
